<a href="https://colab.research.google.com/github/rayalanigama-crypto/Nascomlab-CSEB/blob/main/linearalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt

np.set_printoptions(precision=3, suppress=True)
np.random.seed(42)
print('Setup complete. NumPy', np.__version__)

In [ ]:
import numpy as np
scalar = np.array(6)
vector = np.array([1, 4, 8])
matrix = np.array([[5, 8], [2, 4]])
tensor = np.ones((2, 9, 5))
for name, arr in [('scalar', scalar), ('vector', vector),
                  ('matrix', matrix), ('tensor', tensor)]:
    print(f'{name:7s} ndim={arr.ndim}  shape={arr.shape}')

scalar  ndim=0  shape=()
vector  ndim=1  shape=(3,)
matrix  ndim=2  shape=(2, 2)
tensor  ndim=3  shape=(2, 9, 5)


In [ ]:
A = np.arange(9).reshape(3, 3)
B = np.ones((3, 3), dtype=int)

print('A:\n', A)
print('A + B', A + B)
print('A.T ', A.T.shape, '):\n', A.T)
print('A.reshape', A.reshape(3,3))
print('A.flatten():', A.flatten())

A:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
A + B [[1 2 3]
 [4 5 6]
 [7 8 9]]
A.T  (3, 3) ):
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
A.reshape [[0 1 2]
 [3 4 5]
 [6 7 8]]
A.flatten(): [0 1 2 3 4 5 6 7 8]


In [ ]:
a = np.array([2, 6, 3])
b = np.array([1, 4,5])
print('a . b ', np.dot(a, b))
print('a x b', np.cross(a, b))

a . b  41
a x b [18 -7  2]


In [ ]:
import numpy as np
import numpy.linalg as la

print('L2 norm  ||a||_2 :', la.norm(a))
print('L1 norm  ||a||_1 :', la.norm(a, 1))
print('Linf norm        :', la.norm(a, np.inf))
def cosine(u, v):
    return np.dot(u, v) / (la.norm(u) * la.norm(v))

print('cosine(a, b)     :', round(cosine(a, b), 5))

L2 norm  ||a||_2 : 7.0
L1 norm  ||a||_1 : 11.0
Linf norm        : 6.0
cosine(a, b)     : 0.90378
